import { S3Client, PutObjectCommand, GetObjectCommand } from '@aws-sdk/client-s3';
import { getSignedUrl } from '@aws-sdk/s3-request-presigner';
import dotenv from 'dotenv';
dotenv.config();

export const s3 = new S3Client({
  region: process.env.AWS_REGION || 'us-east-1',
  credentials: {
    accessKeyId:     process.env.AWS_ACCESS_KEY_ID,
    secretAccessKey: process.env.AWS_SECRET_ACCESS_KEY,
  },
});

export const BUCKET        = process.env.S3_BUCKET_NAME;
export const THUMB_BUCKET  = process.env.S3_THUMBNAIL_BUCKET;

/**
 * Generate a pre-signed PUT URL so the browser uploads directly to S3.
 * Expires in 5 minutes.
 */
export const getUploadPresignedUrl = async (key, contentType) => {
  const cmd = new PutObjectCommand({
    Bucket:      BUCKET,
    Key:         key,
    ContentType: contentType,
  });
  return getSignedUrl(s3, cmd, { expiresIn: 300 });
};

/**
 * Public URL of an object in the main bucket.
 */
export const publicUrl = (key) =>
  `https://${BUCKET}.s3.${process.env.AWS_REGION || 'us-east-1'}.amazonaws.com/${key}`;

/**
 * Public URL of a thumbnail (generated by Lambda in the thumbnail bucket).
 */
export const thumbUrl = (key) =>
  `https://${THUMB_BUCKET}.s3.${process.env.AWS_REGION || 'us-east-1'}.amazonaws.com/thumb-${key}`;
